apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ovdttx94k-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ovdttx94k-go 
  name: ovdttx94k-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ovdttx94k-go 
